### ISSUE TITLE
Multiple readers on Fifo

### ISSUE THREAD

**Issue by harnyk** [sweepbright/iter-helpers#7]
Consider the following scenario:

```ts
const f = new Fifo<number>();

async function foo() {
    for await (const item of f) {
        console.log('foo:', item);
    }
}

async function bar() {
    for await (const item of f) {
        console.log('bar:', item);
    }
}

await Promise.all([
    foo(),
    bar(),
    chain(range(0, 10))
        .tap(async (item) => {
            await f.waitDrain();
            f.push(item);
        })
        .onEnd(async () => {
            f.end();
        })
        .consume(),
]);

```

We feed the range of numbers from 0 to 9 to the fifo.

At the same time two functions `foo` and `bar` are running in parallel.
They both are iterating over the fifo.

### Expected behavior:
 - some values are consumed by `foo`, some by `bar`
 - the distribution is not deterministic and in real life it depends on the speed of consumer for-await-of loops
 - it is important that all the values will be evenly consumed by some of the consumers, without skipping or duplicating
 - example output:

```
foo: 0
bar: 1
foo: 2
bar: 3
foo: 4
bar: 5
foo: 6
bar: 7
foo: 8
bar: 9
```

### Actual behavior:
- the process is stuck due to the deadlock

### Affected components

 - `Fifo`
 - `Fifo`-based:
    - `Mux`
    - `ConcurrentMap`
    - `Bufferize`

### Real life application

I don't know if `Fifo` is used anywhere in this manner. It's probably not, because
this functionality has never worked properly.

But we can imagine a scenario, where one queue is listened to by many workers, and the payload is always processed by a free worker.

### Solution

I am actively working on my new library - https://github.com/harnyk/chan, which has a similar behavior but with the bug fixed.

I propose to use it instead of `Fifo`, and make `Fifo` a shim around it.

Also I encourage to use a new asynchronous method `send` instead of the combination of `waitDrain` and `push`.

**Comment by vazhoha** [comment]
Closed by #8
